// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm9qW9QCBTnf98p8GMCbZSr-RoicG8yDA',
    appId: '1:230900685679:web:648268ac5b49cad983e69a',
    messagingSenderId: '230900685679',
    projectId: 'roameo-a1746',
    authDomain: 'roameo-a1746.firebaseapp.com',
    storageBucket: 'roameo-a1746.firebasestorage.app',
    measurementId: 'G-Y443MCD5JY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY37hYTkNueSKOUNeX2oloUO5FzUu5ns8',
    appId: '1:230900685679:ios:e28c2bd7e6e7204883e69a',
    messagingSenderId: '230900685679',
    projectId: 'roameo-a1746',
    storageBucket: 'roameo-a1746.firebasestorage.app',
    iosBundleId: 'com.example.newFlu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm9qW9QCBTnf98p8GMCbZSr-RoicG8yDA',
    appId: '1:230900685679:web:768b7843d8ae25ad83e69a',
    messagingSenderId: '230900685679',
    projectId: 'roameo-a1746',
    authDomain: 'roameo-a1746.firebaseapp.com',
    storageBucket: 'roameo-a1746.firebasestorage.app',
    measurementId: 'G-LV60K6Z8FT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY37hYTkNueSKOUNeX2oloUO5FzUu5ns8',
    appId: '1:230900685679:ios:e28c2bd7e6e7204883e69a',
    messagingSenderId: '230900685679',
    projectId: 'roameo-a1746',
    storageBucket: 'roameo-a1746.firebasestorage.app',
    iosBundleId: 'com.example.newFlu',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUOdccaYeWko6gtq3pWl4_DEyQ96DfZVM',
    appId: '1:230900685679:android:f298e6a0255e142d83e69a',
    messagingSenderId: '230900685679',
    projectId: 'roameo-a1746',
    storageBucket: 'roameo-a1746.firebasestorage.app',
  );

}