name: explore_page
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8
  carousel_slider: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting package
  flutter_lints: ^5.0.0

flutter:
  # Enables material design icons
  uses-material-design: true

  # Asset paths for icons
  assets:
    - assets/icons/homeicon.png
    - assets/icons/homeonclick.png
    - assets/icons/chaticon.png
    - assets/icons/aiicon.png
    - assets/icons/exploreicon.png
    - assets/icons/exploreonclick.png
    - assets/icons/feedicon.png
    - assets/icons/feedonclick.png
    - assets/images/Galle.png
    - assets/images/Hambanthota.png
    - assets/images/Dambulla.png
    - assets/images/Ella.png
    - assets/images/Kandy.jpg
    - assets/images/Anuradhapura.jpg
    - assets/images/Mirissa.jpg
    - assets/images/Nuwaraeliya.jpg
    - assets/images/Trinco.jpg
    - assets/images/Colombo.jpg
    - assets/images/Jaffna.jpg
    - assets/images/Udawalawe.jpg
