name: Run FastAPI Tests

on:
  push:
    branches: [ "ci-cd-pipeline" ]
  pull_request:
    branches: [ "ci-cd-pipeline" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up environment variables
      run: echo "FIREBASE_CREDENTIALS='${{ secrets.FIREBASE_CREDENTIALS }}'" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir fastapi firebase-admin bcrypt pyjwt pytest httpx flake8
        if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi

    - name: Verify Flake8 installation
      run: flake8 --version

    - name: Lint with flake8
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: python -m pytest tests/
